### ISSUE TITLE
input이 제대로 작동하지 않음.

### ISSUE THREAD

**Issue by KmMnJn** [jil8885/scheduler-cli#10]
![2018-05-18 10 28 08](https://user-images.githubusercontent.com/31723018/40237244-cf8f349c-5aea-11e8-82ac-f02e1dfdabe8.png)

You can omit "in {category}". 라는 말이 성립하지 않음.

**Comment by jil8885** [comment]
해당 이슈는 0.0.2 버전에 해결하여 테스트 겸 다시 업로드를 했으니 다시 테스트 부탁드립니다.
