### ISSUE TITLE
show 기능 추가

### ISSUE THREAD

**Issue by KmMnJn** [jil8885/scheduler-cli#11]
중요표시를 한 데이터 or 시간순으로 데이터를 정렬 하여 보여 주거나, 카테고리 혹은 원하는 날짜에 해당하는 show를 구현하기를 바람

**Comment by jil8885** [comment]
0.0.4 버전부터 원하는 카테고리나 날짜에 해당하는 스케쥴만 보이도록 했으며,
차기 릴리스인 0.0.9부터는 시간순으로 일정을 배열하도록 변경했습니다.
