### ISSUE TITLE
이미 delete 한 list를 다시 delete 할때, 안내문 출력 바람.

### ISSUE THREAD

**Issue by KmMnJn** [jil8885/scheduler-cli#14]
![2018-05-18 10 38 35](https://user-images.githubusercontent.com/31723018/40237715-37b6b81e-5aec-11e8-9545-0029cf1e6888.png)

사진 참고

**Comment by jil8885** [comment]
0.0.6 버전부터 delete 기능을 실행시켰을 때, 안내문과 함께 지워진 스케쥴 표를 출력하도록 바꾸었습니다.
