### ISSUE TITLE
현재 날짜와 비교하여 이전에 끝내야 하는 일정을 따로 보여주는 기능 추가

### ISSUE THREAD

**Issue by KmMnJn** [jil8885/scheduler-cli#17]
프로그램을 실행한 날짜가 5월 31일때 5월 31일 이전에 종료 되야 하는 기능 추가.

**Comment by jil8885** [comment]
코드 상으로는 이미 구현이 되었고 차기 버전에서 overdue 항목으로 들어갈 예정입니다
