### ISSUE TITLE
category별 삭제 기능을 추가해주세요.

### ISSUE THREAD

**Issue by KmMnJn** [jil8885/scheduler-cli#22]
존재하는 카테고리에 대한 삭제 명령이 들어 왔을때, 삭제 할 수 있는 기능을 추가해 주세여.

**Comment by jil8885** [comment]
https://github.com/jil8885/scheduler-cli/commit/441cbf54cea0fc6fe17205fc959833d56fe91964
해당 커밋에서 존재하는 카테고리에 대해 삭제명령이 추가됨.
