### ISSUE TITLE
처음 나오는 help를 수정해 주세요.

### ISSUE THREAD

**Issue by KmMnJn** [jil8885/scheduler-cli#23]
help 명령을 입력 했을때 나오는 화면이랑, 처음에 나오는 화면이 다릅니다.

**Comment by jil8885** [comment]
https://github.com/jil8885/scheduler-cli/commit/be7d47ee67436b9418ef2afd35cae493964504f7
해당 커밋에서 초기 메뉴와 같게 출력되도록 수정됨.
