### ISSUE TITLE
help를 풍부하게 만들 필요가 있습니다.

### ISSUE THREAD

**Issue by KmMnJn** [jil8885/scheduler-cli#28]
달력 보기가 구현은 되어 있지만, help와 위키에 적혀 있지 않아 히든 메뉴가 되어버렸습니다.
위키 혹은 help에 구현된 모든 기능을 서술 합시다.

**Comment by jil8885** [comment]
https://github.com/jil8885/scheduler-cli/commit/04da03c4a45451121e49fdf859d5e60b55d8ae3d
해당 커밋에서 수정되었습니다
