### ISSUE TITLE
help(도움말)부분 구별표시

### ISSUE THREAD

**Issue by hyobins** [jil8885/scheduler-cli#4]
도움말 부분이 한눈에 들어오지 않습니다.
박스 또는 선으로 뚜렷하게 표시를 하면 더 좋을 것 같습니다

**Comment by jil8885** [comment]
0.0.3부터 터미널에 색깔과 함께 각 명령어 별로 기능과 예시를 help를 입력할 때 출력하도록 바꾸었습니다.
