### ISSUE TITLE
일정의 중요도 및 due date 순서대로 정렬 출력

### ISSUE THREAD

**Issue by MoonJeWoong** [jil8885/scheduler-cli#7]
일정마다 사용자가 중요도나 마감기한을 정하여 원하는 기준으로 순서대로 출력이 되게 구현하면 편리할 것 같습니다.

**Comment by jil8885** [comment]
기준을 정하는 명령어가 따로 있으면 좋겠는데 이에 대한 생각이 있으신가요?

**Comment by jil8885** [comment]
0.0.9버전부터 id 순서대로 배열이 아닌 마감기한이 빠른 순서대로 배열하게 되었습니다.
