### ISSUE TITLE
input에 대한 설명을 보강하자!

### ISSUE THREAD

**Issue by KmMnJn** [jil8885/scheduler-cli#9]
To add schedule, input "add {due(ex.3/2)} {content} in {category}". You can omit "in {category}".
를
To add schedule, input "add {due} {content} in {category}". You can omit "in {category}".
ex) input add 5/18 test in test    OR    input add 5/18 test
로 수정 하자!

**Comment by jil8885** [comment]
0.0.5 버전 이상부터 새로운 매뉴얼로 개편과 함께 반영했습니다
